### ISSUE TITLE
Drony never stops even after wifi is disconnected 

### ISSUE THREAD

**Issue by nisargjhaveri** [SuppSandroB/sandrop#127]
On Android 6.0, Drony 1.3.112

**Comment by SuppSandroB** [comment]
Try that Drony is started not manuall but with wifi appearing. There is switch in settings to enable this.

**Comment by nisargjhaveri** [comment]
Yes, I have that option enabled for my WiFi. It starts properly. But doesn't stop automatically.

**Comment by nisargjhaveri** [comment]
Anything?

I noticed that it stopped when WiFi disconnected a few times. But most of the time it does't stop. It is really frustrating as at that point Internet doesn't work even on data until I go and specifically stop Drony.

**Comment by nisargjhaveri** [comment]
Happy to help you need any more information or help. :)

**Comment by SuppSandroB** [comment]
Will retest it. You can get more info what is going on by using adb logcat.
https://www.youtube.com/watch?v=wv1x24CZrvY

**Comment by nisargjhaveri** [comment]
These are some of the lines from logcat that I think might be relevant. These are only the lines which contains "drony", If I should look for something else too, let me know.

```
03-19 00:41:30.062   865   876 V ActivityManager_MU: isSingleton(org.sandroproxy.drony, ApplicationInfo{c2d4794 org.sandroproxy.drony}, org.sandroproxy.drony.net.ConectivityChangeReceiver, 0x0) = false
03-19 00:41:30.090 16849 16849 D ActivityThread: BDC-Calling onReceive: intent=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 cmp=org.sandroproxy.drony/.net.ConectivityChangeReceiver (has extras) }, receiver=org.sandroproxy.drony.net.ConectivityChangeReceiver@adbfcb2
03-19 00:41:30.091 16849 16849 D ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 cmp=org.sandroproxy.drony/.net.ConectivityChangeReceiver (has extras) } packageName=org.sandroproxy.drony resultCode=0 resultData=null resultExtras=null}
03-19 00:41:30.129   865  1285 V ActivityManager_MU: isSingleton(org.sandroproxy.drony, ApplicationInfo{c2d4794 org.sandroproxy.drony}, org.sandroproxy.drony.net.ConectivityChangeReceiver, 0x0) = false
03-19 00:41:30.141 16849 16849 D ActivityThread: BDC-Calling onReceive: intent=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 cmp=org.sandroproxy.drony/.net.ConectivityChangeReceiver (has extras) }, receiver=org.sandroproxy.drony.net.ConectivityChangeReceiver@a550403
03-19 00:41:30.144 16849 16849 D ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 cmp=org.sandroproxy.drony/.net.ConectivityChangeReceiver (has extras) } packageName=org.sandroproxy.drony resultCode=0 resultData=null resultExtras=null}
03-19 00:41:30.171 16849 16877 D DronyApplication:  onLost Release default network from 1312
03-19 00:41:30.171 16849 16877 W System.err: 	at org.sandroproxy.drony.DronyApplication.a(DronyApplication.java:2752)
03-19 00:41:30.171 16849 16877 W System.err: 	at org.sandroproxy.drony.j.onLost(DronyApplication.java:836)
03-19 00:41:30.345   865  2425 V ActivityManager_MU: isSingleton(org.sandroproxy.drony, ApplicationInfo{c2d4794 org.sandroproxy.drony}, org.sandroproxy.drony.net.ConectivityChangeReceiver, 0x0) = false
03-19 00:41:30.374 16849 19561 D Posix   : [Posix_connect Debug]Process org.sandroproxy.drony :8019 
03-19 00:41:30.395 16849 16849 D ActivityThread: BDC-Calling onReceive: intent=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 cmp=org.sandroproxy.drony/.net.ConectivityChangeReceiver (has extras) }, receiver=org.sandroproxy.drony.net.ConectivityChangeReceiver@50a89b9
03-19 00:41:30.395 16849 16849 D ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 cmp=org.sandroproxy.drony/.net.ConectivityChangeReceiver (has extras) } packageName=org.sandroproxy.drony resultCode=0 resultData=null resultExtras=null}
03-19 00:41:30.536 16849 19718 W System.err: 	at org.sandroproxy.drony.DronyApplication.j(DronyApplication.java:719)
```

After this similar pattern repeats, and after some more lines, only `System.err` keeps coming. Hope it'll be helpful.

**Comment by SuppSandroB** [comment]
Will look at the code and prepare some modification so that you can test. Please send mail to supp.sandrob@gmail.com so I can send you apk to test.
